// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CHAPTER_AUTO_RECORD.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHAPTER_AUTO_RECORD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Id            *uint32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Seconds       *uint32                `protobuf:"varint,3,req,name=seconds" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CHAPTER_AUTO_RECORD) Reset() {
	*x = CHAPTER_AUTO_RECORD{}
	mi := &file_CHAPTER_AUTO_RECORD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CHAPTER_AUTO_RECORD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CHAPTER_AUTO_RECORD) ProtoMessage() {}

func (x *CHAPTER_AUTO_RECORD) ProtoReflect() protoreflect.Message {
	mi := &file_CHAPTER_AUTO_RECORD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CHAPTER_AUTO_RECORD.ProtoReflect.Descriptor instead.
func (*CHAPTER_AUTO_RECORD) Descriptor() ([]byte, []int) {
	return file_CHAPTER_AUTO_RECORD_proto_rawDescGZIP(), []int{0}
}

func (x *CHAPTER_AUTO_RECORD) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CHAPTER_AUTO_RECORD) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CHAPTER_AUTO_RECORD) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

var File_CHAPTER_AUTO_RECORD_proto protoreflect.FileDescriptor

const file_CHAPTER_AUTO_RECORD_proto_rawDesc = "" +
	"\n" +
	"\x19CHAPTER_AUTO_RECORD.proto\x12\abelfast\"S\n" +
	"\x13CHAPTER_AUTO_RECORD\x12\x12\n" +
	"\x04type\x18\x01 \x02(\rR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\rR\x02id\x12\x18\n" +
	"\aseconds\x18\x03 \x02(\rR\asecondsB\fZ\n" +
	"./protobuf"

var (
	file_CHAPTER_AUTO_RECORD_proto_rawDescOnce sync.Once
	file_CHAPTER_AUTO_RECORD_proto_rawDescData []byte
)

func file_CHAPTER_AUTO_RECORD_proto_rawDescGZIP() []byte {
	file_CHAPTER_AUTO_RECORD_proto_rawDescOnce.Do(func() {
		file_CHAPTER_AUTO_RECORD_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CHAPTER_AUTO_RECORD_proto_rawDesc), len(file_CHAPTER_AUTO_RECORD_proto_rawDesc)))
	})
	return file_CHAPTER_AUTO_RECORD_proto_rawDescData
}

var file_CHAPTER_AUTO_RECORD_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CHAPTER_AUTO_RECORD_proto_goTypes = []any{
	(*CHAPTER_AUTO_RECORD)(nil), // 0: belfast.CHAPTER_AUTO_RECORD
}
var file_CHAPTER_AUTO_RECORD_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CHAPTER_AUTO_RECORD_proto_init() }
func file_CHAPTER_AUTO_RECORD_proto_init() {
	if File_CHAPTER_AUTO_RECORD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CHAPTER_AUTO_RECORD_proto_rawDesc), len(file_CHAPTER_AUTO_RECORD_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CHAPTER_AUTO_RECORD_proto_goTypes,
		DependencyIndexes: file_CHAPTER_AUTO_RECORD_proto_depIdxs,
		MessageInfos:      file_CHAPTER_AUTO_RECORD_proto_msgTypes,
	}.Build()
	File_CHAPTER_AUTO_RECORD_proto = out.File
	file_CHAPTER_AUTO_RECORD_proto_goTypes = nil
	file_CHAPTER_AUTO_RECORD_proto_depIdxs = nil
}
