// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: CS_11034.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_11034 struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LoadingPicOpenFlag *uint32                `protobuf:"varint,1,req,name=loading_pic_open_flag,json=loadingPicOpenFlag" json:"loading_pic_open_flag,omitempty"`
	LoadingPicIdList_1 []uint32               `protobuf:"varint,2,rep,name=loading_pic_id_list_1,json=loadingPicIdList1" json:"loading_pic_id_list_1,omitempty"`
	LoadingPicIdList_2 []uint32               `protobuf:"varint,3,rep,name=loading_pic_id_list_2,json=loadingPicIdList2" json:"loading_pic_id_list_2,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CS_11034) Reset() {
	*x = CS_11034{}
	mi := &file_CS_11034_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_11034) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_11034) ProtoMessage() {}

func (x *CS_11034) ProtoReflect() protoreflect.Message {
	mi := &file_CS_11034_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_11034.ProtoReflect.Descriptor instead.
func (*CS_11034) Descriptor() ([]byte, []int) {
	return file_CS_11034_proto_rawDescGZIP(), []int{0}
}

func (x *CS_11034) GetLoadingPicOpenFlag() uint32 {
	if x != nil && x.LoadingPicOpenFlag != nil {
		return *x.LoadingPicOpenFlag
	}
	return 0
}

func (x *CS_11034) GetLoadingPicIdList_1() []uint32 {
	if x != nil {
		return x.LoadingPicIdList_1
	}
	return nil
}

func (x *CS_11034) GetLoadingPicIdList_2() []uint32 {
	if x != nil {
		return x.LoadingPicIdList_2
	}
	return nil
}

var File_CS_11034_proto protoreflect.FileDescriptor

const file_CS_11034_proto_rawDesc = "" +
	"\n" +
	"\x0eCS_11034.proto\x12\abelfast\"\xa1\x01\n" +
	"\bCS_11034\x121\n" +
	"\x15loading_pic_open_flag\x18\x01 \x02(\rR\x12loadingPicOpenFlag\x120\n" +
	"\x15loading_pic_id_list_1\x18\x02 \x03(\rR\x11loadingPicIdList1\x120\n" +
	"\x15loading_pic_id_list_2\x18\x03 \x03(\rR\x11loadingPicIdList2B\fZ\n" +
	"./protobuf"

var (
	file_CS_11034_proto_rawDescOnce sync.Once
	file_CS_11034_proto_rawDescData []byte
)

func file_CS_11034_proto_rawDescGZIP() []byte {
	file_CS_11034_proto_rawDescOnce.Do(func() {
		file_CS_11034_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CS_11034_proto_rawDesc), len(file_CS_11034_proto_rawDesc)))
	})
	return file_CS_11034_proto_rawDescData
}

var file_CS_11034_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CS_11034_proto_goTypes = []any{
	(*CS_11034)(nil), // 0: belfast.CS_11034
}
var file_CS_11034_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CS_11034_proto_init() }
func file_CS_11034_proto_init() {
	if File_CS_11034_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CS_11034_proto_rawDesc), len(file_CS_11034_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CS_11034_proto_goTypes,
		DependencyIndexes: file_CS_11034_proto_depIdxs,
		MessageInfos:      file_CS_11034_proto_msgTypes,
	}.Build()
	File_CS_11034_proto = out.File
	file_CS_11034_proto_goTypes = nil
	file_CS_11034_proto_depIdxs = nil
}
