// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ACTIVITY_MALL.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ACTIVITY_MALL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *uint32                `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	Gold          *uint32                `protobuf:"varint,2,req,name=gold" json:"gold,omitempty"`
	Round         *uint32                `protobuf:"varint,3,req,name=round" json:"round,omitempty"`
	Order         *PB_ORDER              `protobuf:"bytes,4,req,name=order" json:"order,omitempty"`
	StoryList     []uint32               `protobuf:"varint,5,rep,name=story_list,json=storyList" json:"story_list,omitempty"`
	EmployeeList  []*PB_EMPLOYEE         `protobuf:"bytes,6,rep,name=employee_list,json=employeeList" json:"employee_list,omitempty"`
	FloorList     []*PB_FLOOR            `protobuf:"bytes,7,rep,name=floor_list,json=floorList" json:"floor_list,omitempty"`
	LastRound     *PB_LAST_ROUND         `protobuf:"bytes,8,opt,name=last_round,json=lastRound" json:"last_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_ACTIVITY_MALL) Reset() {
	*x = PB_ACTIVITY_MALL{}
	mi := &file_PB_ACTIVITY_MALL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ACTIVITY_MALL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ACTIVITY_MALL) ProtoMessage() {}

func (x *PB_ACTIVITY_MALL) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ACTIVITY_MALL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ACTIVITY_MALL.ProtoReflect.Descriptor instead.
func (*PB_ACTIVITY_MALL) Descriptor() ([]byte, []int) {
	return file_PB_ACTIVITY_MALL_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ACTIVITY_MALL) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *PB_ACTIVITY_MALL) GetGold() uint32 {
	if x != nil && x.Gold != nil {
		return *x.Gold
	}
	return 0
}

func (x *PB_ACTIVITY_MALL) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *PB_ACTIVITY_MALL) GetOrder() *PB_ORDER {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PB_ACTIVITY_MALL) GetStoryList() []uint32 {
	if x != nil {
		return x.StoryList
	}
	return nil
}

func (x *PB_ACTIVITY_MALL) GetEmployeeList() []*PB_EMPLOYEE {
	if x != nil {
		return x.EmployeeList
	}
	return nil
}

func (x *PB_ACTIVITY_MALL) GetFloorList() []*PB_FLOOR {
	if x != nil {
		return x.FloorList
	}
	return nil
}

func (x *PB_ACTIVITY_MALL) GetLastRound() *PB_LAST_ROUND {
	if x != nil {
		return x.LastRound
	}
	return nil
}

var File_PB_ACTIVITY_MALL_proto protoreflect.FileDescriptor

const file_PB_ACTIVITY_MALL_proto_rawDesc = "" +
	"\n" +
	"\x16PB_ACTIVITY_MALL.proto\x12\abelfast\x1a\x11PB_EMPLOYEE.proto\x1a\x0ePB_FLOOR.proto\x1a\x13PB_LAST_ROUND.proto\x1a\x0ePB_ORDER.proto\"\xbe\x02\n" +
	"\x10PB_ACTIVITY_MALL\x12\x14\n" +
	"\x05level\x18\x01 \x02(\rR\x05level\x12\x12\n" +
	"\x04gold\x18\x02 \x02(\rR\x04gold\x12\x14\n" +
	"\x05round\x18\x03 \x02(\rR\x05round\x12'\n" +
	"\x05order\x18\x04 \x02(\v2\x11.belfast.PB_ORDERR\x05order\x12\x1d\n" +
	"\n" +
	"story_list\x18\x05 \x03(\rR\tstoryList\x129\n" +
	"\remployee_list\x18\x06 \x03(\v2\x14.belfast.PB_EMPLOYEER\femployeeList\x120\n" +
	"\n" +
	"floor_list\x18\a \x03(\v2\x11.belfast.PB_FLOORR\tfloorList\x125\n" +
	"\n" +
	"last_round\x18\b \x01(\v2\x16.belfast.PB_LAST_ROUNDR\tlastRoundB\fZ\n" +
	"./protobuf"

var (
	file_PB_ACTIVITY_MALL_proto_rawDescOnce sync.Once
	file_PB_ACTIVITY_MALL_proto_rawDescData []byte
)

func file_PB_ACTIVITY_MALL_proto_rawDescGZIP() []byte {
	file_PB_ACTIVITY_MALL_proto_rawDescOnce.Do(func() {
		file_PB_ACTIVITY_MALL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ACTIVITY_MALL_proto_rawDesc), len(file_PB_ACTIVITY_MALL_proto_rawDesc)))
	})
	return file_PB_ACTIVITY_MALL_proto_rawDescData
}

var file_PB_ACTIVITY_MALL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ACTIVITY_MALL_proto_goTypes = []any{
	(*PB_ACTIVITY_MALL)(nil), // 0: belfast.PB_ACTIVITY_MALL
	(*PB_ORDER)(nil),         // 1: belfast.PB_ORDER
	(*PB_EMPLOYEE)(nil),      // 2: belfast.PB_EMPLOYEE
	(*PB_FLOOR)(nil),         // 3: belfast.PB_FLOOR
	(*PB_LAST_ROUND)(nil),    // 4: belfast.PB_LAST_ROUND
}
var file_PB_ACTIVITY_MALL_proto_depIdxs = []int32{
	1, // 0: belfast.PB_ACTIVITY_MALL.order:type_name -> belfast.PB_ORDER
	2, // 1: belfast.PB_ACTIVITY_MALL.employee_list:type_name -> belfast.PB_EMPLOYEE
	3, // 2: belfast.PB_ACTIVITY_MALL.floor_list:type_name -> belfast.PB_FLOOR
	4, // 3: belfast.PB_ACTIVITY_MALL.last_round:type_name -> belfast.PB_LAST_ROUND
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_PB_ACTIVITY_MALL_proto_init() }
func file_PB_ACTIVITY_MALL_proto_init() {
	if File_PB_ACTIVITY_MALL_proto != nil {
		return
	}
	file_PB_EMPLOYEE_proto_init()
	file_PB_FLOOR_proto_init()
	file_PB_LAST_ROUND_proto_init()
	file_PB_ORDER_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ACTIVITY_MALL_proto_rawDesc), len(file_PB_ACTIVITY_MALL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ACTIVITY_MALL_proto_goTypes,
		DependencyIndexes: file_PB_ACTIVITY_MALL_proto_depIdxs,
		MessageInfos:      file_PB_ACTIVITY_MALL_proto_msgTypes,
	}.Build()
	File_PB_ACTIVITY_MALL_proto = out.File
	file_PB_ACTIVITY_MALL_proto_goTypes = nil
	file_PB_ACTIVITY_MALL_proto_depIdxs = nil
}
