// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_EMPLOYEE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_EMPLOYEE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Tid           *uint32                `protobuf:"varint,2,req,name=tid" json:"tid,omitempty"`
	AttrList      []*KEYVALUE_P11        `protobuf:"bytes,3,rep,name=attr_list,json=attrList" json:"attr_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_EMPLOYEE) Reset() {
	*x = PB_EMPLOYEE{}
	mi := &file_PB_EMPLOYEE_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_EMPLOYEE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_EMPLOYEE) ProtoMessage() {}

func (x *PB_EMPLOYEE) ProtoReflect() protoreflect.Message {
	mi := &file_PB_EMPLOYEE_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_EMPLOYEE.ProtoReflect.Descriptor instead.
func (*PB_EMPLOYEE) Descriptor() ([]byte, []int) {
	return file_PB_EMPLOYEE_proto_rawDescGZIP(), []int{0}
}

func (x *PB_EMPLOYEE) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PB_EMPLOYEE) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *PB_EMPLOYEE) GetAttrList() []*KEYVALUE_P11 {
	if x != nil {
		return x.AttrList
	}
	return nil
}

var File_PB_EMPLOYEE_proto protoreflect.FileDescriptor

const file_PB_EMPLOYEE_proto_rawDesc = "" +
	"\n" +
	"\x11PB_EMPLOYEE.proto\x12\abelfast\x1a\x12KEYVALUE_P11.proto\"c\n" +
	"\vPB_EMPLOYEE\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x10\n" +
	"\x03tid\x18\x02 \x02(\rR\x03tid\x122\n" +
	"\tattr_list\x18\x03 \x03(\v2\x15.belfast.KEYVALUE_P11R\battrListB\fZ\n" +
	"./protobuf"

var (
	file_PB_EMPLOYEE_proto_rawDescOnce sync.Once
	file_PB_EMPLOYEE_proto_rawDescData []byte
)

func file_PB_EMPLOYEE_proto_rawDescGZIP() []byte {
	file_PB_EMPLOYEE_proto_rawDescOnce.Do(func() {
		file_PB_EMPLOYEE_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_EMPLOYEE_proto_rawDesc), len(file_PB_EMPLOYEE_proto_rawDesc)))
	})
	return file_PB_EMPLOYEE_proto_rawDescData
}

var file_PB_EMPLOYEE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_EMPLOYEE_proto_goTypes = []any{
	(*PB_EMPLOYEE)(nil),  // 0: belfast.PB_EMPLOYEE
	(*KEYVALUE_P11)(nil), // 1: belfast.KEYVALUE_P11
}
var file_PB_EMPLOYEE_proto_depIdxs = []int32{
	1, // 0: belfast.PB_EMPLOYEE.attr_list:type_name -> belfast.KEYVALUE_P11
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PB_EMPLOYEE_proto_init() }
func file_PB_EMPLOYEE_proto_init() {
	if File_PB_EMPLOYEE_proto != nil {
		return
	}
	file_KEYVALUE_P11_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_EMPLOYEE_proto_rawDesc), len(file_PB_EMPLOYEE_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_EMPLOYEE_proto_goTypes,
		DependencyIndexes: file_PB_EMPLOYEE_proto_depIdxs,
		MessageInfos:      file_PB_EMPLOYEE_proto_msgTypes,
	}.Build()
	File_PB_EMPLOYEE_proto = out.File
	file_PB_EMPLOYEE_proto_goTypes = nil
	file_PB_EMPLOYEE_proto_depIdxs = nil
}
