// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_LAST_ROUND.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_LAST_ROUND struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *uint32                `protobuf:"varint,1,req,name=balance" json:"balance,omitempty"`
	FloorIncome   []uint32               `protobuf:"varint,2,rep,name=floor_income,json=floorIncome" json:"floor_income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_LAST_ROUND) Reset() {
	*x = PB_LAST_ROUND{}
	mi := &file_PB_LAST_ROUND_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_LAST_ROUND) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_LAST_ROUND) ProtoMessage() {}

func (x *PB_LAST_ROUND) ProtoReflect() protoreflect.Message {
	mi := &file_PB_LAST_ROUND_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_LAST_ROUND.ProtoReflect.Descriptor instead.
func (*PB_LAST_ROUND) Descriptor() ([]byte, []int) {
	return file_PB_LAST_ROUND_proto_rawDescGZIP(), []int{0}
}

func (x *PB_LAST_ROUND) GetBalance() uint32 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *PB_LAST_ROUND) GetFloorIncome() []uint32 {
	if x != nil {
		return x.FloorIncome
	}
	return nil
}

var File_PB_LAST_ROUND_proto protoreflect.FileDescriptor

const file_PB_LAST_ROUND_proto_rawDesc = "" +
	"\n" +
	"\x13PB_LAST_ROUND.proto\x12\abelfast\"L\n" +
	"\rPB_LAST_ROUND\x12\x18\n" +
	"\abalance\x18\x01 \x02(\rR\abalance\x12!\n" +
	"\ffloor_income\x18\x02 \x03(\rR\vfloorIncomeB\fZ\n" +
	"./protobuf"

var (
	file_PB_LAST_ROUND_proto_rawDescOnce sync.Once
	file_PB_LAST_ROUND_proto_rawDescData []byte
)

func file_PB_LAST_ROUND_proto_rawDescGZIP() []byte {
	file_PB_LAST_ROUND_proto_rawDescOnce.Do(func() {
		file_PB_LAST_ROUND_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_LAST_ROUND_proto_rawDesc), len(file_PB_LAST_ROUND_proto_rawDesc)))
	})
	return file_PB_LAST_ROUND_proto_rawDescData
}

var file_PB_LAST_ROUND_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_LAST_ROUND_proto_goTypes = []any{
	(*PB_LAST_ROUND)(nil), // 0: belfast.PB_LAST_ROUND
}
var file_PB_LAST_ROUND_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_LAST_ROUND_proto_init() }
func file_PB_LAST_ROUND_proto_init() {
	if File_PB_LAST_ROUND_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_LAST_ROUND_proto_rawDesc), len(file_PB_LAST_ROUND_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_LAST_ROUND_proto_goTypes,
		DependencyIndexes: file_PB_LAST_ROUND_proto_depIdxs,
		MessageInfos:      file_PB_LAST_ROUND_proto_msgTypes,
	}.Build()
	File_PB_LAST_ROUND_proto = out.File
	file_PB_LAST_ROUND_proto_goTypes = nil
	file_PB_LAST_ROUND_proto_depIdxs = nil
}
