// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ORDER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ORDER struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurOrder        *uint32                `protobuf:"varint,1,req,name=cur_order,json=curOrder" json:"cur_order,omitempty"`
	ActiveTime      *uint32                `protobuf:"varint,2,req,name=active_time,json=activeTime" json:"active_time,omitempty"`
	EmployeeList    []uint32               `protobuf:"varint,3,rep,name=employee_list,json=employeeList" json:"employee_list,omitempty"`
	FinishOrderList []uint32               `protobuf:"varint,4,rep,name=finish_order_list,json=finishOrderList" json:"finish_order_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PB_ORDER) Reset() {
	*x = PB_ORDER{}
	mi := &file_PB_ORDER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ORDER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ORDER) ProtoMessage() {}

func (x *PB_ORDER) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ORDER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ORDER.ProtoReflect.Descriptor instead.
func (*PB_ORDER) Descriptor() ([]byte, []int) {
	return file_PB_ORDER_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ORDER) GetCurOrder() uint32 {
	if x != nil && x.CurOrder != nil {
		return *x.CurOrder
	}
	return 0
}

func (x *PB_ORDER) GetActiveTime() uint32 {
	if x != nil && x.ActiveTime != nil {
		return *x.ActiveTime
	}
	return 0
}

func (x *PB_ORDER) GetEmployeeList() []uint32 {
	if x != nil {
		return x.EmployeeList
	}
	return nil
}

func (x *PB_ORDER) GetFinishOrderList() []uint32 {
	if x != nil {
		return x.FinishOrderList
	}
	return nil
}

var File_PB_ORDER_proto protoreflect.FileDescriptor

const file_PB_ORDER_proto_rawDesc = "" +
	"\n" +
	"\x0ePB_ORDER.proto\x12\abelfast\"\x99\x01\n" +
	"\bPB_ORDER\x12\x1b\n" +
	"\tcur_order\x18\x01 \x02(\rR\bcurOrder\x12\x1f\n" +
	"\vactive_time\x18\x02 \x02(\rR\n" +
	"activeTime\x12#\n" +
	"\remployee_list\x18\x03 \x03(\rR\femployeeList\x12*\n" +
	"\x11finish_order_list\x18\x04 \x03(\rR\x0ffinishOrderListB\fZ\n" +
	"./protobuf"

var (
	file_PB_ORDER_proto_rawDescOnce sync.Once
	file_PB_ORDER_proto_rawDescData []byte
)

func file_PB_ORDER_proto_rawDescGZIP() []byte {
	file_PB_ORDER_proto_rawDescOnce.Do(func() {
		file_PB_ORDER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ORDER_proto_rawDesc), len(file_PB_ORDER_proto_rawDesc)))
	})
	return file_PB_ORDER_proto_rawDescData
}

var file_PB_ORDER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ORDER_proto_goTypes = []any{
	(*PB_ORDER)(nil), // 0: belfast.PB_ORDER
}
var file_PB_ORDER_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_ORDER_proto_init() }
func file_PB_ORDER_proto_init() {
	if File_PB_ORDER_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ORDER_proto_rawDesc), len(file_PB_ORDER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ORDER_proto_goTypes,
		DependencyIndexes: file_PB_ORDER_proto_depIdxs,
		MessageInfos:      file_PB_ORDER_proto_msgTypes,
	}.Build()
	File_PB_ORDER_proto = out.File
	file_PB_ORDER_proto_goTypes = nil
	file_PB_ORDER_proto_depIdxs = nil
}
