// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_PLAYER_RANK.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_PLAYER_RANK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PTGC_PLAYER           `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	Score         *uint32                `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_PLAYER_RANK) Reset() {
	*x = PTGC_PLAYER_RANK{}
	mi := &file_PTGC_PLAYER_RANK_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_PLAYER_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_PLAYER_RANK) ProtoMessage() {}

func (x *PTGC_PLAYER_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_PLAYER_RANK_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_PLAYER_RANK.ProtoReflect.Descriptor instead.
func (*PTGC_PLAYER_RANK) Descriptor() ([]byte, []int) {
	return file_PTGC_PLAYER_RANK_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_PLAYER_RANK) GetPlayer() *PTGC_PLAYER {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PTGC_PLAYER_RANK) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_PTGC_PLAYER_RANK_proto protoreflect.FileDescriptor

const file_PTGC_PLAYER_RANK_proto_rawDesc = "" +
	"\n" +
	"\x16PTGC_PLAYER_RANK.proto\x12\abelfast\x1a\x11PTGC_PLAYER.proto\"V\n" +
	"\x10PTGC_PLAYER_RANK\x12,\n" +
	"\x06player\x18\x01 \x02(\v2\x14.belfast.PTGC_PLAYERR\x06player\x12\x14\n" +
	"\x05score\x18\x02 \x02(\rR\x05scoreB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_PLAYER_RANK_proto_rawDescOnce sync.Once
	file_PTGC_PLAYER_RANK_proto_rawDescData []byte
)

func file_PTGC_PLAYER_RANK_proto_rawDescGZIP() []byte {
	file_PTGC_PLAYER_RANK_proto_rawDescOnce.Do(func() {
		file_PTGC_PLAYER_RANK_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_PLAYER_RANK_proto_rawDesc), len(file_PTGC_PLAYER_RANK_proto_rawDesc)))
	})
	return file_PTGC_PLAYER_RANK_proto_rawDescData
}

var file_PTGC_PLAYER_RANK_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_PLAYER_RANK_proto_goTypes = []any{
	(*PTGC_PLAYER_RANK)(nil), // 0: belfast.PTGC_PLAYER_RANK
	(*PTGC_PLAYER)(nil),      // 1: belfast.PTGC_PLAYER
}
var file_PTGC_PLAYER_RANK_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_PLAYER_RANK.player:type_name -> belfast.PTGC_PLAYER
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PTGC_PLAYER_RANK_proto_init() }
func file_PTGC_PLAYER_RANK_proto_init() {
	if File_PTGC_PLAYER_RANK_proto != nil {
		return
	}
	file_PTGC_PLAYER_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_PLAYER_RANK_proto_rawDesc), len(file_PTGC_PLAYER_RANK_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_PLAYER_RANK_proto_goTypes,
		DependencyIndexes: file_PTGC_PLAYER_RANK_proto_depIdxs,
		MessageInfos:      file_PTGC_PLAYER_RANK_proto_msgTypes,
	}.Build()
	File_PTGC_PLAYER_RANK_proto = out.File
	file_PTGC_PLAYER_RANK_proto_goTypes = nil
	file_PTGC_PLAYER_RANK_proto_depIdxs = nil
}
