// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_CHEAT_BAR_PLAYER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_CHEAT_BAR_PLAYER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint32                `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Seat          *uint32                `protobuf:"varint,2,req,name=seat" json:"seat,omitempty"`
	CardNum       *uint32                `protobuf:"varint,3,req,name=card_num,json=cardNum" json:"card_num,omitempty"`
	BombList      []*PTGC_CHEAT_BAR_BOMB `protobuf:"bytes,4,rep,name=bomb_list,json=bombList" json:"bomb_list,omitempty"`
	IsAuto        *uint32                `protobuf:"varint,5,req,name=is_auto,json=isAuto" json:"is_auto,omitempty"`
	RoundNum      *uint32                `protobuf:"varint,6,req,name=round_num,json=roundNum" json:"round_num,omitempty"`
	PlayerInfo    *PTGC_PLAYER           `protobuf:"bytes,7,req,name=player_info,json=playerInfo" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_CHEAT_BAR_PLAYER) Reset() {
	*x = PTGC_CHEAT_BAR_PLAYER{}
	mi := &file_PTGC_CHEAT_BAR_PLAYER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_CHEAT_BAR_PLAYER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_CHEAT_BAR_PLAYER) ProtoMessage() {}

func (x *PTGC_CHEAT_BAR_PLAYER) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_CHEAT_BAR_PLAYER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_CHEAT_BAR_PLAYER.ProtoReflect.Descriptor instead.
func (*PTGC_CHEAT_BAR_PLAYER) Descriptor() ([]byte, []int) {
	return file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetSeat() uint32 {
	if x != nil && x.Seat != nil {
		return *x.Seat
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetCardNum() uint32 {
	if x != nil && x.CardNum != nil {
		return *x.CardNum
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetBombList() []*PTGC_CHEAT_BAR_BOMB {
	if x != nil {
		return x.BombList
	}
	return nil
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetIsAuto() uint32 {
	if x != nil && x.IsAuto != nil {
		return *x.IsAuto
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetRoundNum() uint32 {
	if x != nil && x.RoundNum != nil {
		return *x.RoundNum
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_PLAYER) GetPlayerInfo() *PTGC_PLAYER {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_PTGC_CHEAT_BAR_PLAYER_proto protoreflect.FileDescriptor

const file_PTGC_CHEAT_BAR_PLAYER_proto_rawDesc = "" +
	"\n" +
	"\x1bPTGC_CHEAT_BAR_PLAYER.proto\x12\abelfast\x1a\x19PTGC_CHEAT_BAR_BOMB.proto\x1a\x11PTGC_PLAYER.proto\"\x87\x02\n" +
	"\x15PTGC_CHEAT_BAR_PLAYER\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\rR\x06userId\x12\x12\n" +
	"\x04seat\x18\x02 \x02(\rR\x04seat\x12\x19\n" +
	"\bcard_num\x18\x03 \x02(\rR\acardNum\x129\n" +
	"\tbomb_list\x18\x04 \x03(\v2\x1c.belfast.PTGC_CHEAT_BAR_BOMBR\bbombList\x12\x17\n" +
	"\ais_auto\x18\x05 \x02(\rR\x06isAuto\x12\x1b\n" +
	"\tround_num\x18\x06 \x02(\rR\broundNum\x125\n" +
	"\vplayer_info\x18\a \x02(\v2\x14.belfast.PTGC_PLAYERR\n" +
	"playerInfoB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescOnce sync.Once
	file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescData []byte
)

func file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescGZIP() []byte {
	file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescOnce.Do(func() {
		file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_CHEAT_BAR_PLAYER_proto_rawDesc), len(file_PTGC_CHEAT_BAR_PLAYER_proto_rawDesc)))
	})
	return file_PTGC_CHEAT_BAR_PLAYER_proto_rawDescData
}

var file_PTGC_CHEAT_BAR_PLAYER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_CHEAT_BAR_PLAYER_proto_goTypes = []any{
	(*PTGC_CHEAT_BAR_PLAYER)(nil), // 0: belfast.PTGC_CHEAT_BAR_PLAYER
	(*PTGC_CHEAT_BAR_BOMB)(nil),   // 1: belfast.PTGC_CHEAT_BAR_BOMB
	(*PTGC_PLAYER)(nil),           // 2: belfast.PTGC_PLAYER
}
var file_PTGC_CHEAT_BAR_PLAYER_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_CHEAT_BAR_PLAYER.bomb_list:type_name -> belfast.PTGC_CHEAT_BAR_BOMB
	2, // 1: belfast.PTGC_CHEAT_BAR_PLAYER.player_info:type_name -> belfast.PTGC_PLAYER
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PTGC_CHEAT_BAR_PLAYER_proto_init() }
func file_PTGC_CHEAT_BAR_PLAYER_proto_init() {
	if File_PTGC_CHEAT_BAR_PLAYER_proto != nil {
		return
	}
	file_PTGC_CHEAT_BAR_BOMB_proto_init()
	file_PTGC_PLAYER_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_CHEAT_BAR_PLAYER_proto_rawDesc), len(file_PTGC_CHEAT_BAR_PLAYER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_CHEAT_BAR_PLAYER_proto_goTypes,
		DependencyIndexes: file_PTGC_CHEAT_BAR_PLAYER_proto_depIdxs,
		MessageInfos:      file_PTGC_CHEAT_BAR_PLAYER_proto_msgTypes,
	}.Build()
	File_PTGC_CHEAT_BAR_PLAYER_proto = out.File
	file_PTGC_CHEAT_BAR_PLAYER_proto_goTypes = nil
	file_PTGC_CHEAT_BAR_PLAYER_proto_depIdxs = nil
}
