// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_BID_KING_EVENT_EFFECT.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_BID_KING_EVENT_EFFECT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *uint32                `protobuf:"varint,1,req,name=event_id,json=eventId" json:"event_id,omitempty"`
	IntValue      *uint32                `protobuf:"varint,2,req,name=int_value,json=intValue" json:"int_value,omitempty"`
	ItemList      []*PTGC_BID_KING_ITEM  `protobuf:"bytes,3,rep,name=item_list,json=itemList" json:"item_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_BID_KING_EVENT_EFFECT) Reset() {
	*x = PTGC_BID_KING_EVENT_EFFECT{}
	mi := &file_PTGC_BID_KING_EVENT_EFFECT_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_BID_KING_EVENT_EFFECT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_BID_KING_EVENT_EFFECT) ProtoMessage() {}

func (x *PTGC_BID_KING_EVENT_EFFECT) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_BID_KING_EVENT_EFFECT_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_BID_KING_EVENT_EFFECT.ProtoReflect.Descriptor instead.
func (*PTGC_BID_KING_EVENT_EFFECT) Descriptor() ([]byte, []int) {
	return file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_BID_KING_EVENT_EFFECT) GetEventId() uint32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *PTGC_BID_KING_EVENT_EFFECT) GetIntValue() uint32 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *PTGC_BID_KING_EVENT_EFFECT) GetItemList() []*PTGC_BID_KING_ITEM {
	if x != nil {
		return x.ItemList
	}
	return nil
}

var File_PTGC_BID_KING_EVENT_EFFECT_proto protoreflect.FileDescriptor

const file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDesc = "" +
	"\n" +
	" PTGC_BID_KING_EVENT_EFFECT.proto\x12\abelfast\x1a\x18PTGC_BID_KING_ITEM.proto\"\x8e\x01\n" +
	"\x1aPTGC_BID_KING_EVENT_EFFECT\x12\x19\n" +
	"\bevent_id\x18\x01 \x02(\rR\aeventId\x12\x1b\n" +
	"\tint_value\x18\x02 \x02(\rR\bintValue\x128\n" +
	"\titem_list\x18\x03 \x03(\v2\x1b.belfast.PTGC_BID_KING_ITEMR\bitemListB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescOnce sync.Once
	file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescData []byte
)

func file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescGZIP() []byte {
	file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescOnce.Do(func() {
		file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDesc), len(file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDesc)))
	})
	return file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDescData
}

var file_PTGC_BID_KING_EVENT_EFFECT_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_BID_KING_EVENT_EFFECT_proto_goTypes = []any{
	(*PTGC_BID_KING_EVENT_EFFECT)(nil), // 0: belfast.PTGC_BID_KING_EVENT_EFFECT
	(*PTGC_BID_KING_ITEM)(nil),         // 1: belfast.PTGC_BID_KING_ITEM
}
var file_PTGC_BID_KING_EVENT_EFFECT_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_BID_KING_EVENT_EFFECT.item_list:type_name -> belfast.PTGC_BID_KING_ITEM
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PTGC_BID_KING_EVENT_EFFECT_proto_init() }
func file_PTGC_BID_KING_EVENT_EFFECT_proto_init() {
	if File_PTGC_BID_KING_EVENT_EFFECT_proto != nil {
		return
	}
	file_PTGC_BID_KING_ITEM_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDesc), len(file_PTGC_BID_KING_EVENT_EFFECT_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_BID_KING_EVENT_EFFECT_proto_goTypes,
		DependencyIndexes: file_PTGC_BID_KING_EVENT_EFFECT_proto_depIdxs,
		MessageInfos:      file_PTGC_BID_KING_EVENT_EFFECT_proto_msgTypes,
	}.Build()
	File_PTGC_BID_KING_EVENT_EFFECT_proto = out.File
	file_PTGC_BID_KING_EVENT_EFFECT_proto_goTypes = nil
	file_PTGC_BID_KING_EVENT_EFFECT_proto_depIdxs = nil
}
