// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_LOAD.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_LOAD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint32                `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Load          *uint32                `protobuf:"varint,2,req,name=load" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_LOAD) Reset() {
	*x = PTGC_LOAD{}
	mi := &file_PTGC_LOAD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_LOAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_LOAD) ProtoMessage() {}

func (x *PTGC_LOAD) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_LOAD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_LOAD.ProtoReflect.Descriptor instead.
func (*PTGC_LOAD) Descriptor() ([]byte, []int) {
	return file_PTGC_LOAD_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_LOAD) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *PTGC_LOAD) GetLoad() uint32 {
	if x != nil && x.Load != nil {
		return *x.Load
	}
	return 0
}

var File_PTGC_LOAD_proto protoreflect.FileDescriptor

const file_PTGC_LOAD_proto_rawDesc = "" +
	"\n" +
	"\x0fPTGC_LOAD.proto\x12\abelfast\"8\n" +
	"\tPTGC_LOAD\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\rR\x06userId\x12\x12\n" +
	"\x04load\x18\x02 \x02(\rR\x04loadB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_LOAD_proto_rawDescOnce sync.Once
	file_PTGC_LOAD_proto_rawDescData []byte
)

func file_PTGC_LOAD_proto_rawDescGZIP() []byte {
	file_PTGC_LOAD_proto_rawDescOnce.Do(func() {
		file_PTGC_LOAD_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_LOAD_proto_rawDesc), len(file_PTGC_LOAD_proto_rawDesc)))
	})
	return file_PTGC_LOAD_proto_rawDescData
}

var file_PTGC_LOAD_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_LOAD_proto_goTypes = []any{
	(*PTGC_LOAD)(nil), // 0: belfast.PTGC_LOAD
}
var file_PTGC_LOAD_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PTGC_LOAD_proto_init() }
func file_PTGC_LOAD_proto_init() {
	if File_PTGC_LOAD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_LOAD_proto_rawDesc), len(file_PTGC_LOAD_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_LOAD_proto_goTypes,
		DependencyIndexes: file_PTGC_LOAD_proto_depIdxs,
		MessageInfos:      file_PTGC_LOAD_proto_msgTypes,
	}.Build()
	File_PTGC_LOAD_proto = out.File
	file_PTGC_LOAD_proto_goTypes = nil
	file_PTGC_LOAD_proto_depIdxs = nil
}
