// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_GAME_USER_VIEW.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_GAME_USER_VIEW struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      *uint32                `protobuf:"varint,1,req,name=game_type,json=gameType" json:"game_type,omitempty"`
	ShipId        *uint32                `protobuf:"varint,2,req,name=ship_id,json=shipId" json:"ship_id,omitempty"`
	SkinId        *uint32                `protobuf:"varint,3,req,name=skin_id,json=skinId" json:"skin_id,omitempty"`
	Color         *uint32                `protobuf:"varint,4,req,name=color" json:"color,omitempty"`
	DressList     []uint32               `protobuf:"varint,5,rep,name=dress_list,json=dressList" json:"dress_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_GAME_USER_VIEW) Reset() {
	*x = PTGC_GAME_USER_VIEW{}
	mi := &file_PTGC_GAME_USER_VIEW_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_GAME_USER_VIEW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_GAME_USER_VIEW) ProtoMessage() {}

func (x *PTGC_GAME_USER_VIEW) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_GAME_USER_VIEW_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_GAME_USER_VIEW.ProtoReflect.Descriptor instead.
func (*PTGC_GAME_USER_VIEW) Descriptor() ([]byte, []int) {
	return file_PTGC_GAME_USER_VIEW_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_GAME_USER_VIEW) GetGameType() uint32 {
	if x != nil && x.GameType != nil {
		return *x.GameType
	}
	return 0
}

func (x *PTGC_GAME_USER_VIEW) GetShipId() uint32 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

func (x *PTGC_GAME_USER_VIEW) GetSkinId() uint32 {
	if x != nil && x.SkinId != nil {
		return *x.SkinId
	}
	return 0
}

func (x *PTGC_GAME_USER_VIEW) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

func (x *PTGC_GAME_USER_VIEW) GetDressList() []uint32 {
	if x != nil {
		return x.DressList
	}
	return nil
}

var File_PTGC_GAME_USER_VIEW_proto protoreflect.FileDescriptor

const file_PTGC_GAME_USER_VIEW_proto_rawDesc = "" +
	"\n" +
	"\x19PTGC_GAME_USER_VIEW.proto\x12\abelfast\"\x99\x01\n" +
	"\x13PTGC_GAME_USER_VIEW\x12\x1b\n" +
	"\tgame_type\x18\x01 \x02(\rR\bgameType\x12\x17\n" +
	"\aship_id\x18\x02 \x02(\rR\x06shipId\x12\x17\n" +
	"\askin_id\x18\x03 \x02(\rR\x06skinId\x12\x14\n" +
	"\x05color\x18\x04 \x02(\rR\x05color\x12\x1d\n" +
	"\n" +
	"dress_list\x18\x05 \x03(\rR\tdressListB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_GAME_USER_VIEW_proto_rawDescOnce sync.Once
	file_PTGC_GAME_USER_VIEW_proto_rawDescData []byte
)

func file_PTGC_GAME_USER_VIEW_proto_rawDescGZIP() []byte {
	file_PTGC_GAME_USER_VIEW_proto_rawDescOnce.Do(func() {
		file_PTGC_GAME_USER_VIEW_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_GAME_USER_VIEW_proto_rawDesc), len(file_PTGC_GAME_USER_VIEW_proto_rawDesc)))
	})
	return file_PTGC_GAME_USER_VIEW_proto_rawDescData
}

var file_PTGC_GAME_USER_VIEW_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_GAME_USER_VIEW_proto_goTypes = []any{
	(*PTGC_GAME_USER_VIEW)(nil), // 0: belfast.PTGC_GAME_USER_VIEW
}
var file_PTGC_GAME_USER_VIEW_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PTGC_GAME_USER_VIEW_proto_init() }
func file_PTGC_GAME_USER_VIEW_proto_init() {
	if File_PTGC_GAME_USER_VIEW_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_GAME_USER_VIEW_proto_rawDesc), len(file_PTGC_GAME_USER_VIEW_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_GAME_USER_VIEW_proto_goTypes,
		DependencyIndexes: file_PTGC_GAME_USER_VIEW_proto_depIdxs,
		MessageInfos:      file_PTGC_GAME_USER_VIEW_proto_msgTypes,
	}.Build()
	File_PTGC_GAME_USER_VIEW_proto = out.File
	file_PTGC_GAME_USER_VIEW_proto_goTypes = nil
	file_PTGC_GAME_USER_VIEW_proto_depIdxs = nil
}
