// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_BID_KING_ITEM.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_BID_KING_ITEM struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Uid           *uint32                   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Id            *uint32                   `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Rarity        *uint32                   `protobuf:"varint,3,req,name=rarity" json:"rarity,omitempty"`
	Pos           []*PTGC_BID_KING_ITEM_POS `protobuf:"bytes,4,rep,name=pos" json:"pos,omitempty"`
	Price         *uint32                   `protobuf:"varint,5,req,name=price" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_BID_KING_ITEM) Reset() {
	*x = PTGC_BID_KING_ITEM{}
	mi := &file_PTGC_BID_KING_ITEM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_BID_KING_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_BID_KING_ITEM) ProtoMessage() {}

func (x *PTGC_BID_KING_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_BID_KING_ITEM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_BID_KING_ITEM.ProtoReflect.Descriptor instead.
func (*PTGC_BID_KING_ITEM) Descriptor() ([]byte, []int) {
	return file_PTGC_BID_KING_ITEM_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_BID_KING_ITEM) GetUid() uint32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *PTGC_BID_KING_ITEM) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PTGC_BID_KING_ITEM) GetRarity() uint32 {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return 0
}

func (x *PTGC_BID_KING_ITEM) GetPos() []*PTGC_BID_KING_ITEM_POS {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PTGC_BID_KING_ITEM) GetPrice() uint32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

var File_PTGC_BID_KING_ITEM_proto protoreflect.FileDescriptor

const file_PTGC_BID_KING_ITEM_proto_rawDesc = "" +
	"\n" +
	"\x18PTGC_BID_KING_ITEM.proto\x12\abelfast\x1a\x1cPTGC_BID_KING_ITEM_POS.proto\"\x97\x01\n" +
	"\x12PTGC_BID_KING_ITEM\x12\x10\n" +
	"\x03uid\x18\x01 \x02(\rR\x03uid\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\rR\x02id\x12\x16\n" +
	"\x06rarity\x18\x03 \x02(\rR\x06rarity\x121\n" +
	"\x03pos\x18\x04 \x03(\v2\x1f.belfast.PTGC_BID_KING_ITEM_POSR\x03pos\x12\x14\n" +
	"\x05price\x18\x05 \x02(\rR\x05priceB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_BID_KING_ITEM_proto_rawDescOnce sync.Once
	file_PTGC_BID_KING_ITEM_proto_rawDescData []byte
)

func file_PTGC_BID_KING_ITEM_proto_rawDescGZIP() []byte {
	file_PTGC_BID_KING_ITEM_proto_rawDescOnce.Do(func() {
		file_PTGC_BID_KING_ITEM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_ITEM_proto_rawDesc), len(file_PTGC_BID_KING_ITEM_proto_rawDesc)))
	})
	return file_PTGC_BID_KING_ITEM_proto_rawDescData
}

var file_PTGC_BID_KING_ITEM_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_BID_KING_ITEM_proto_goTypes = []any{
	(*PTGC_BID_KING_ITEM)(nil),     // 0: belfast.PTGC_BID_KING_ITEM
	(*PTGC_BID_KING_ITEM_POS)(nil), // 1: belfast.PTGC_BID_KING_ITEM_POS
}
var file_PTGC_BID_KING_ITEM_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_BID_KING_ITEM.pos:type_name -> belfast.PTGC_BID_KING_ITEM_POS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PTGC_BID_KING_ITEM_proto_init() }
func file_PTGC_BID_KING_ITEM_proto_init() {
	if File_PTGC_BID_KING_ITEM_proto != nil {
		return
	}
	file_PTGC_BID_KING_ITEM_POS_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_ITEM_proto_rawDesc), len(file_PTGC_BID_KING_ITEM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_BID_KING_ITEM_proto_goTypes,
		DependencyIndexes: file_PTGC_BID_KING_ITEM_proto_depIdxs,
		MessageInfos:      file_PTGC_BID_KING_ITEM_proto_msgTypes,
	}.Build()
	File_PTGC_BID_KING_ITEM_proto = out.File
	file_PTGC_BID_KING_ITEM_proto_goTypes = nil
	file_PTGC_BID_KING_ITEM_proto_depIdxs = nil
}
