// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_CHEAT_BAR_CARD.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_CHEAT_BAR_CARD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *uint32                `protobuf:"varint,1,req,name=key" json:"key,omitempty"`
	Id            *uint32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_CHEAT_BAR_CARD) Reset() {
	*x = PTGC_CHEAT_BAR_CARD{}
	mi := &file_PTGC_CHEAT_BAR_CARD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_CHEAT_BAR_CARD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_CHEAT_BAR_CARD) ProtoMessage() {}

func (x *PTGC_CHEAT_BAR_CARD) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_CHEAT_BAR_CARD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_CHEAT_BAR_CARD.ProtoReflect.Descriptor instead.
func (*PTGC_CHEAT_BAR_CARD) Descriptor() ([]byte, []int) {
	return file_PTGC_CHEAT_BAR_CARD_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_CHEAT_BAR_CARD) GetKey() uint32 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *PTGC_CHEAT_BAR_CARD) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

var File_PTGC_CHEAT_BAR_CARD_proto protoreflect.FileDescriptor

const file_PTGC_CHEAT_BAR_CARD_proto_rawDesc = "" +
	"\n" +
	"\x19PTGC_CHEAT_BAR_CARD.proto\x12\abelfast\"7\n" +
	"\x13PTGC_CHEAT_BAR_CARD\x12\x10\n" +
	"\x03key\x18\x01 \x02(\rR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\rR\x02idB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_CHEAT_BAR_CARD_proto_rawDescOnce sync.Once
	file_PTGC_CHEAT_BAR_CARD_proto_rawDescData []byte
)

func file_PTGC_CHEAT_BAR_CARD_proto_rawDescGZIP() []byte {
	file_PTGC_CHEAT_BAR_CARD_proto_rawDescOnce.Do(func() {
		file_PTGC_CHEAT_BAR_CARD_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_CHEAT_BAR_CARD_proto_rawDesc), len(file_PTGC_CHEAT_BAR_CARD_proto_rawDesc)))
	})
	return file_PTGC_CHEAT_BAR_CARD_proto_rawDescData
}

var file_PTGC_CHEAT_BAR_CARD_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_CHEAT_BAR_CARD_proto_goTypes = []any{
	(*PTGC_CHEAT_BAR_CARD)(nil), // 0: belfast.PTGC_CHEAT_BAR_CARD
}
var file_PTGC_CHEAT_BAR_CARD_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PTGC_CHEAT_BAR_CARD_proto_init() }
func file_PTGC_CHEAT_BAR_CARD_proto_init() {
	if File_PTGC_CHEAT_BAR_CARD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_CHEAT_BAR_CARD_proto_rawDesc), len(file_PTGC_CHEAT_BAR_CARD_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_CHEAT_BAR_CARD_proto_goTypes,
		DependencyIndexes: file_PTGC_CHEAT_BAR_CARD_proto_depIdxs,
		MessageInfos:      file_PTGC_CHEAT_BAR_CARD_proto_msgTypes,
	}.Build()
	File_PTGC_CHEAT_BAR_CARD_proto = out.File
	file_PTGC_CHEAT_BAR_CARD_proto_goTypes = nil
	file_PTGC_CHEAT_BAR_CARD_proto_depIdxs = nil
}
