// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_PLAYER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_PLAYER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Level         *uint32                `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Name          *string                `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	GuildName     *string                `protobuf:"bytes,4,req,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	Display       *DISPLAYINFO           `protobuf:"bytes,5,opt,name=display" json:"display,omitempty"`
	UserView      []*PTGC_GAME_USER_VIEW `protobuf:"bytes,6,rep,name=user_view,json=userView" json:"user_view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_PLAYER) Reset() {
	*x = PTGC_PLAYER{}
	mi := &file_PTGC_PLAYER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_PLAYER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_PLAYER) ProtoMessage() {}

func (x *PTGC_PLAYER) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_PLAYER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_PLAYER.ProtoReflect.Descriptor instead.
func (*PTGC_PLAYER) Descriptor() ([]byte, []int) {
	return file_PTGC_PLAYER_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_PLAYER) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PTGC_PLAYER) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *PTGC_PLAYER) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PTGC_PLAYER) GetGuildName() string {
	if x != nil && x.GuildName != nil {
		return *x.GuildName
	}
	return ""
}

func (x *PTGC_PLAYER) GetDisplay() *DISPLAYINFO {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *PTGC_PLAYER) GetUserView() []*PTGC_GAME_USER_VIEW {
	if x != nil {
		return x.UserView
	}
	return nil
}

var File_PTGC_PLAYER_proto protoreflect.FileDescriptor

const file_PTGC_PLAYER_proto_rawDesc = "" +
	"\n" +
	"\x11PTGC_PLAYER.proto\x12\abelfast\x1a\x11DISPLAYINFO.proto\x1a\x19PTGC_GAME_USER_VIEW.proto\"\xd1\x01\n" +
	"\vPTGC_PLAYER\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x02(\rR\x05level\x12\x12\n" +
	"\x04name\x18\x03 \x02(\tR\x04name\x12\x1d\n" +
	"\n" +
	"guild_name\x18\x04 \x02(\tR\tguildName\x12.\n" +
	"\adisplay\x18\x05 \x01(\v2\x14.belfast.DISPLAYINFOR\adisplay\x129\n" +
	"\tuser_view\x18\x06 \x03(\v2\x1c.belfast.PTGC_GAME_USER_VIEWR\buserViewB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_PLAYER_proto_rawDescOnce sync.Once
	file_PTGC_PLAYER_proto_rawDescData []byte
)

func file_PTGC_PLAYER_proto_rawDescGZIP() []byte {
	file_PTGC_PLAYER_proto_rawDescOnce.Do(func() {
		file_PTGC_PLAYER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_PLAYER_proto_rawDesc), len(file_PTGC_PLAYER_proto_rawDesc)))
	})
	return file_PTGC_PLAYER_proto_rawDescData
}

var file_PTGC_PLAYER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_PLAYER_proto_goTypes = []any{
	(*PTGC_PLAYER)(nil),         // 0: belfast.PTGC_PLAYER
	(*DISPLAYINFO)(nil),         // 1: belfast.DISPLAYINFO
	(*PTGC_GAME_USER_VIEW)(nil), // 2: belfast.PTGC_GAME_USER_VIEW
}
var file_PTGC_PLAYER_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_PLAYER.display:type_name -> belfast.DISPLAYINFO
	2, // 1: belfast.PTGC_PLAYER.user_view:type_name -> belfast.PTGC_GAME_USER_VIEW
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PTGC_PLAYER_proto_init() }
func file_PTGC_PLAYER_proto_init() {
	if File_PTGC_PLAYER_proto != nil {
		return
	}
	file_DISPLAYINFO_proto_init()
	file_PTGC_GAME_USER_VIEW_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_PLAYER_proto_rawDesc), len(file_PTGC_PLAYER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_PLAYER_proto_goTypes,
		DependencyIndexes: file_PTGC_PLAYER_proto_depIdxs,
		MessageInfos:      file_PTGC_PLAYER_proto_msgTypes,
	}.Build()
	File_PTGC_PLAYER_proto = out.File
	file_PTGC_PLAYER_proto_goTypes = nil
	file_PTGC_PLAYER_proto_depIdxs = nil
}
