// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_BID_KING_PLAYER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_BID_KING_PLAYER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint32                `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Sort          *uint32                `protobuf:"varint,2,req,name=sort" json:"sort,omitempty"`
	PlayerInfo    *PTGC_PLAYER           `protobuf:"bytes,3,req,name=player_info,json=playerInfo" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_BID_KING_PLAYER) Reset() {
	*x = PTGC_BID_KING_PLAYER{}
	mi := &file_PTGC_BID_KING_PLAYER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_BID_KING_PLAYER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_BID_KING_PLAYER) ProtoMessage() {}

func (x *PTGC_BID_KING_PLAYER) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_BID_KING_PLAYER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_BID_KING_PLAYER.ProtoReflect.Descriptor instead.
func (*PTGC_BID_KING_PLAYER) Descriptor() ([]byte, []int) {
	return file_PTGC_BID_KING_PLAYER_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_BID_KING_PLAYER) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *PTGC_BID_KING_PLAYER) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *PTGC_BID_KING_PLAYER) GetPlayerInfo() *PTGC_PLAYER {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_PTGC_BID_KING_PLAYER_proto protoreflect.FileDescriptor

const file_PTGC_BID_KING_PLAYER_proto_rawDesc = "" +
	"\n" +
	"\x1aPTGC_BID_KING_PLAYER.proto\x12\abelfast\x1a\x11PTGC_PLAYER.proto\"z\n" +
	"\x14PTGC_BID_KING_PLAYER\x12\x17\n" +
	"\auser_id\x18\x01 \x02(\rR\x06userId\x12\x12\n" +
	"\x04sort\x18\x02 \x02(\rR\x04sort\x125\n" +
	"\vplayer_info\x18\x03 \x02(\v2\x14.belfast.PTGC_PLAYERR\n" +
	"playerInfoB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_BID_KING_PLAYER_proto_rawDescOnce sync.Once
	file_PTGC_BID_KING_PLAYER_proto_rawDescData []byte
)

func file_PTGC_BID_KING_PLAYER_proto_rawDescGZIP() []byte {
	file_PTGC_BID_KING_PLAYER_proto_rawDescOnce.Do(func() {
		file_PTGC_BID_KING_PLAYER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_PLAYER_proto_rawDesc), len(file_PTGC_BID_KING_PLAYER_proto_rawDesc)))
	})
	return file_PTGC_BID_KING_PLAYER_proto_rawDescData
}

var file_PTGC_BID_KING_PLAYER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_BID_KING_PLAYER_proto_goTypes = []any{
	(*PTGC_BID_KING_PLAYER)(nil), // 0: belfast.PTGC_BID_KING_PLAYER
	(*PTGC_PLAYER)(nil),          // 1: belfast.PTGC_PLAYER
}
var file_PTGC_BID_KING_PLAYER_proto_depIdxs = []int32{
	1, // 0: belfast.PTGC_BID_KING_PLAYER.player_info:type_name -> belfast.PTGC_PLAYER
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PTGC_BID_KING_PLAYER_proto_init() }
func file_PTGC_BID_KING_PLAYER_proto_init() {
	if File_PTGC_BID_KING_PLAYER_proto != nil {
		return
	}
	file_PTGC_PLAYER_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_BID_KING_PLAYER_proto_rawDesc), len(file_PTGC_BID_KING_PLAYER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_BID_KING_PLAYER_proto_goTypes,
		DependencyIndexes: file_PTGC_BID_KING_PLAYER_proto_depIdxs,
		MessageInfos:      file_PTGC_BID_KING_PLAYER_proto_msgTypes,
	}.Build()
	File_PTGC_BID_KING_PLAYER_proto = out.File
	file_PTGC_BID_KING_PLAYER_proto_goTypes = nil
	file_PTGC_BID_KING_PLAYER_proto_depIdxs = nil
}
