// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PTGC_ROOM_SIMPLE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTGC_ROOM_SIMPLE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type          *uint32                `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	GameType      *uint32                `protobuf:"varint,3,req,name=game_type,json=gameType" json:"game_type,omitempty"`
	Name          *string                `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	PlayerNum     *uint32                `protobuf:"varint,5,req,name=player_num,json=playerNum" json:"player_num,omitempty"`
	PlayFlag      *uint32                `protobuf:"varint,6,req,name=play_flag,json=playFlag" json:"play_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTGC_ROOM_SIMPLE) Reset() {
	*x = PTGC_ROOM_SIMPLE{}
	mi := &file_PTGC_ROOM_SIMPLE_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTGC_ROOM_SIMPLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTGC_ROOM_SIMPLE) ProtoMessage() {}

func (x *PTGC_ROOM_SIMPLE) ProtoReflect() protoreflect.Message {
	mi := &file_PTGC_ROOM_SIMPLE_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTGC_ROOM_SIMPLE.ProtoReflect.Descriptor instead.
func (*PTGC_ROOM_SIMPLE) Descriptor() ([]byte, []int) {
	return file_PTGC_ROOM_SIMPLE_proto_rawDescGZIP(), []int{0}
}

func (x *PTGC_ROOM_SIMPLE) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PTGC_ROOM_SIMPLE) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *PTGC_ROOM_SIMPLE) GetGameType() uint32 {
	if x != nil && x.GameType != nil {
		return *x.GameType
	}
	return 0
}

func (x *PTGC_ROOM_SIMPLE) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PTGC_ROOM_SIMPLE) GetPlayerNum() uint32 {
	if x != nil && x.PlayerNum != nil {
		return *x.PlayerNum
	}
	return 0
}

func (x *PTGC_ROOM_SIMPLE) GetPlayFlag() uint32 {
	if x != nil && x.PlayFlag != nil {
		return *x.PlayFlag
	}
	return 0
}

var File_PTGC_ROOM_SIMPLE_proto protoreflect.FileDescriptor

const file_PTGC_ROOM_SIMPLE_proto_rawDesc = "" +
	"\n" +
	"\x16PTGC_ROOM_SIMPLE.proto\x12\abelfast\"\xa3\x01\n" +
	"\x10PTGC_ROOM_SIMPLE\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x02(\rR\x04type\x12\x1b\n" +
	"\tgame_type\x18\x03 \x02(\rR\bgameType\x12\x12\n" +
	"\x04name\x18\x04 \x02(\tR\x04name\x12\x1d\n" +
	"\n" +
	"player_num\x18\x05 \x02(\rR\tplayerNum\x12\x1b\n" +
	"\tplay_flag\x18\x06 \x02(\rR\bplayFlagB\fZ\n" +
	"./protobuf"

var (
	file_PTGC_ROOM_SIMPLE_proto_rawDescOnce sync.Once
	file_PTGC_ROOM_SIMPLE_proto_rawDescData []byte
)

func file_PTGC_ROOM_SIMPLE_proto_rawDescGZIP() []byte {
	file_PTGC_ROOM_SIMPLE_proto_rawDescOnce.Do(func() {
		file_PTGC_ROOM_SIMPLE_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PTGC_ROOM_SIMPLE_proto_rawDesc), len(file_PTGC_ROOM_SIMPLE_proto_rawDesc)))
	})
	return file_PTGC_ROOM_SIMPLE_proto_rawDescData
}

var file_PTGC_ROOM_SIMPLE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PTGC_ROOM_SIMPLE_proto_goTypes = []any{
	(*PTGC_ROOM_SIMPLE)(nil), // 0: belfast.PTGC_ROOM_SIMPLE
}
var file_PTGC_ROOM_SIMPLE_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PTGC_ROOM_SIMPLE_proto_init() }
func file_PTGC_ROOM_SIMPLE_proto_init() {
	if File_PTGC_ROOM_SIMPLE_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PTGC_ROOM_SIMPLE_proto_rawDesc), len(file_PTGC_ROOM_SIMPLE_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PTGC_ROOM_SIMPLE_proto_goTypes,
		DependencyIndexes: file_PTGC_ROOM_SIMPLE_proto_depIdxs,
		MessageInfos:      file_PTGC_ROOM_SIMPLE_proto_msgTypes,
	}.Build()
	File_PTGC_ROOM_SIMPLE_proto = out.File
	file_PTGC_ROOM_SIMPLE_proto_goTypes = nil
	file_PTGC_ROOM_SIMPLE_proto_depIdxs = nil
}
