// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23002.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomList      []*PTGC_ROOM_SIMPLE    `protobuf:"bytes,1,rep,name=room_list,json=roomList" json:"room_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23002) Reset() {
	*x = SC_23002{}
	mi := &file_SC_23002_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23002) ProtoMessage() {}

func (x *SC_23002) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23002_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23002.ProtoReflect.Descriptor instead.
func (*SC_23002) Descriptor() ([]byte, []int) {
	return file_SC_23002_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23002) GetRoomList() []*PTGC_ROOM_SIMPLE {
	if x != nil {
		return x.RoomList
	}
	return nil
}

var File_SC_23002_proto protoreflect.FileDescriptor

const file_SC_23002_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23002.proto\x12\abelfast\x1a\x16PTGC_ROOM_SIMPLE.proto\"B\n" +
	"\bSC_23002\x126\n" +
	"\troom_list\x18\x01 \x03(\v2\x19.belfast.PTGC_ROOM_SIMPLER\broomListB\fZ\n" +
	"./protobuf"

var (
	file_SC_23002_proto_rawDescOnce sync.Once
	file_SC_23002_proto_rawDescData []byte
)

func file_SC_23002_proto_rawDescGZIP() []byte {
	file_SC_23002_proto_rawDescOnce.Do(func() {
		file_SC_23002_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23002_proto_rawDesc), len(file_SC_23002_proto_rawDesc)))
	})
	return file_SC_23002_proto_rawDescData
}

var file_SC_23002_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23002_proto_goTypes = []any{
	(*SC_23002)(nil),         // 0: belfast.SC_23002
	(*PTGC_ROOM_SIMPLE)(nil), // 1: belfast.PTGC_ROOM_SIMPLE
}
var file_SC_23002_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23002.room_list:type_name -> belfast.PTGC_ROOM_SIMPLE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_23002_proto_init() }
func file_SC_23002_proto_init() {
	if File_SC_23002_proto != nil {
		return
	}
	file_PTGC_ROOM_SIMPLE_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23002_proto_rawDesc), len(file_SC_23002_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23002_proto_goTypes,
		DependencyIndexes: file_SC_23002_proto_depIdxs,
		MessageInfos:      file_SC_23002_proto_msgTypes,
	}.Build()
	File_SC_23002_proto = out.File
	file_SC_23002_proto_goTypes = nil
	file_SC_23002_proto_depIdxs = nil
}
