// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23431.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23431 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          *uint32                `protobuf:"varint,1,req,name=gold" json:"gold,omitempty"`
	BuyNum        *uint32                `protobuf:"varint,2,req,name=buy_num,json=buyNum" json:"buy_num,omitempty"`
	MaxProfit     *uint32                `protobuf:"varint,3,req,name=max_profit,json=maxProfit" json:"max_profit,omitempty"`
	AccProfit     *int32                 `protobuf:"varint,4,req,name=acc_profit,json=accProfit" json:"acc_profit,omitempty"`
	ItemList      []uint32               `protobuf:"varint,5,rep,name=item_list,json=itemList" json:"item_list,omitempty"`
	AccBuyPrice   *uint32                `protobuf:"varint,6,req,name=acc_buy_price,json=accBuyPrice" json:"acc_buy_price,omitempty"`
	PreBuyState   *uint32                `protobuf:"varint,7,req,name=pre_buy_state,json=preBuyState" json:"pre_buy_state,omitempty"`
	PreTimestamp  *uint32                `protobuf:"varint,8,req,name=pre_timestamp,json=preTimestamp" json:"pre_timestamp,omitempty"`
	MatchTime     *uint32                `protobuf:"varint,9,req,name=match_time,json=matchTime" json:"match_time,omitempty"`
	IsForbidden   *uint32                `protobuf:"varint,10,req,name=is_forbidden,json=isForbidden" json:"is_forbidden,omitempty"`
	GameNum       *uint32                `protobuf:"varint,11,req,name=game_num,json=gameNum" json:"game_num,omitempty"`
	InactiveNum   *uint32                `protobuf:"varint,12,req,name=inactive_num,json=inactiveNum" json:"inactive_num,omitempty"`
	InactiveState *uint32                `protobuf:"varint,13,req,name=inactive_state,json=inactiveState" json:"inactive_state,omitempty"`
	BackForbidden *uint32                `protobuf:"varint,14,req,name=back_forbidden,json=backForbidden" json:"back_forbidden,omitempty"`
	AccItemPrice  *uint32                `protobuf:"varint,15,req,name=acc_item_price,json=accItemPrice" json:"acc_item_price,omitempty"`
	GetReliefNum  *uint32                `protobuf:"varint,16,req,name=get_relief_num,json=getReliefNum" json:"get_relief_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23431) Reset() {
	*x = SC_23431{}
	mi := &file_SC_23431_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23431) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23431) ProtoMessage() {}

func (x *SC_23431) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23431_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23431.ProtoReflect.Descriptor instead.
func (*SC_23431) Descriptor() ([]byte, []int) {
	return file_SC_23431_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23431) GetGold() uint32 {
	if x != nil && x.Gold != nil {
		return *x.Gold
	}
	return 0
}

func (x *SC_23431) GetBuyNum() uint32 {
	if x != nil && x.BuyNum != nil {
		return *x.BuyNum
	}
	return 0
}

func (x *SC_23431) GetMaxProfit() uint32 {
	if x != nil && x.MaxProfit != nil {
		return *x.MaxProfit
	}
	return 0
}

func (x *SC_23431) GetAccProfit() int32 {
	if x != nil && x.AccProfit != nil {
		return *x.AccProfit
	}
	return 0
}

func (x *SC_23431) GetItemList() []uint32 {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *SC_23431) GetAccBuyPrice() uint32 {
	if x != nil && x.AccBuyPrice != nil {
		return *x.AccBuyPrice
	}
	return 0
}

func (x *SC_23431) GetPreBuyState() uint32 {
	if x != nil && x.PreBuyState != nil {
		return *x.PreBuyState
	}
	return 0
}

func (x *SC_23431) GetPreTimestamp() uint32 {
	if x != nil && x.PreTimestamp != nil {
		return *x.PreTimestamp
	}
	return 0
}

func (x *SC_23431) GetMatchTime() uint32 {
	if x != nil && x.MatchTime != nil {
		return *x.MatchTime
	}
	return 0
}

func (x *SC_23431) GetIsForbidden() uint32 {
	if x != nil && x.IsForbidden != nil {
		return *x.IsForbidden
	}
	return 0
}

func (x *SC_23431) GetGameNum() uint32 {
	if x != nil && x.GameNum != nil {
		return *x.GameNum
	}
	return 0
}

func (x *SC_23431) GetInactiveNum() uint32 {
	if x != nil && x.InactiveNum != nil {
		return *x.InactiveNum
	}
	return 0
}

func (x *SC_23431) GetInactiveState() uint32 {
	if x != nil && x.InactiveState != nil {
		return *x.InactiveState
	}
	return 0
}

func (x *SC_23431) GetBackForbidden() uint32 {
	if x != nil && x.BackForbidden != nil {
		return *x.BackForbidden
	}
	return 0
}

func (x *SC_23431) GetAccItemPrice() uint32 {
	if x != nil && x.AccItemPrice != nil {
		return *x.AccItemPrice
	}
	return 0
}

func (x *SC_23431) GetGetReliefNum() uint32 {
	if x != nil && x.GetReliefNum != nil {
		return *x.GetReliefNum
	}
	return 0
}

var File_SC_23431_proto protoreflect.FileDescriptor

const file_SC_23431_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23431.proto\x12\abelfast\"\x99\x04\n" +
	"\bSC_23431\x12\x12\n" +
	"\x04gold\x18\x01 \x02(\rR\x04gold\x12\x17\n" +
	"\abuy_num\x18\x02 \x02(\rR\x06buyNum\x12\x1d\n" +
	"\n" +
	"max_profit\x18\x03 \x02(\rR\tmaxProfit\x12\x1d\n" +
	"\n" +
	"acc_profit\x18\x04 \x02(\x05R\taccProfit\x12\x1b\n" +
	"\titem_list\x18\x05 \x03(\rR\bitemList\x12\"\n" +
	"\racc_buy_price\x18\x06 \x02(\rR\vaccBuyPrice\x12\"\n" +
	"\rpre_buy_state\x18\a \x02(\rR\vpreBuyState\x12#\n" +
	"\rpre_timestamp\x18\b \x02(\rR\fpreTimestamp\x12\x1d\n" +
	"\n" +
	"match_time\x18\t \x02(\rR\tmatchTime\x12!\n" +
	"\fis_forbidden\x18\n" +
	" \x02(\rR\visForbidden\x12\x19\n" +
	"\bgame_num\x18\v \x02(\rR\agameNum\x12!\n" +
	"\finactive_num\x18\f \x02(\rR\vinactiveNum\x12%\n" +
	"\x0einactive_state\x18\r \x02(\rR\rinactiveState\x12%\n" +
	"\x0eback_forbidden\x18\x0e \x02(\rR\rbackForbidden\x12$\n" +
	"\x0eacc_item_price\x18\x0f \x02(\rR\faccItemPrice\x12$\n" +
	"\x0eget_relief_num\x18\x10 \x02(\rR\fgetReliefNumB\fZ\n" +
	"./protobuf"

var (
	file_SC_23431_proto_rawDescOnce sync.Once
	file_SC_23431_proto_rawDescData []byte
)

func file_SC_23431_proto_rawDescGZIP() []byte {
	file_SC_23431_proto_rawDescOnce.Do(func() {
		file_SC_23431_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23431_proto_rawDesc), len(file_SC_23431_proto_rawDesc)))
	})
	return file_SC_23431_proto_rawDescData
}

var file_SC_23431_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23431_proto_goTypes = []any{
	(*SC_23431)(nil), // 0: belfast.SC_23431
}
var file_SC_23431_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SC_23431_proto_init() }
func file_SC_23431_proto_init() {
	if File_SC_23431_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23431_proto_rawDesc), len(file_SC_23431_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23431_proto_goTypes,
		DependencyIndexes: file_SC_23431_proto_depIdxs,
		MessageInfos:      file_SC_23431_proto_msgTypes,
	}.Build()
	File_SC_23431_proto = out.File
	file_SC_23431_proto_goTypes = nil
	file_SC_23431_proto_depIdxs = nil
}
