// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23095.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23095 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      *uint32                `protobuf:"varint,1,req,name=game_type,json=gameType" json:"game_type,omitempty"`
	PlayerList    []*PTGC_PLAYER         `protobuf:"bytes,2,rep,name=player_list,json=playerList" json:"player_list,omitempty"`
	TeamList      []*PTGC_TEAM           `protobuf:"bytes,3,rep,name=team_list,json=teamList" json:"team_list,omitempty"`
	ReadyList     []uint32               `protobuf:"varint,4,rep,name=ready_list,json=readyList" json:"ready_list,omitempty"`
	Time          *uint32                `protobuf:"varint,5,req,name=time" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23095) Reset() {
	*x = SC_23095{}
	mi := &file_SC_23095_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23095) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23095) ProtoMessage() {}

func (x *SC_23095) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23095_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23095.ProtoReflect.Descriptor instead.
func (*SC_23095) Descriptor() ([]byte, []int) {
	return file_SC_23095_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23095) GetGameType() uint32 {
	if x != nil && x.GameType != nil {
		return *x.GameType
	}
	return 0
}

func (x *SC_23095) GetPlayerList() []*PTGC_PLAYER {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *SC_23095) GetTeamList() []*PTGC_TEAM {
	if x != nil {
		return x.TeamList
	}
	return nil
}

func (x *SC_23095) GetReadyList() []uint32 {
	if x != nil {
		return x.ReadyList
	}
	return nil
}

func (x *SC_23095) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

var File_SC_23095_proto protoreflect.FileDescriptor

const file_SC_23095_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23095.proto\x12\abelfast\x1a\x11PTGC_PLAYER.proto\x1a\x0fPTGC_TEAM.proto\"\xc2\x01\n" +
	"\bSC_23095\x12\x1b\n" +
	"\tgame_type\x18\x01 \x02(\rR\bgameType\x125\n" +
	"\vplayer_list\x18\x02 \x03(\v2\x14.belfast.PTGC_PLAYERR\n" +
	"playerList\x12/\n" +
	"\tteam_list\x18\x03 \x03(\v2\x12.belfast.PTGC_TEAMR\bteamList\x12\x1d\n" +
	"\n" +
	"ready_list\x18\x04 \x03(\rR\treadyList\x12\x12\n" +
	"\x04time\x18\x05 \x02(\rR\x04timeB\fZ\n" +
	"./protobuf"

var (
	file_SC_23095_proto_rawDescOnce sync.Once
	file_SC_23095_proto_rawDescData []byte
)

func file_SC_23095_proto_rawDescGZIP() []byte {
	file_SC_23095_proto_rawDescOnce.Do(func() {
		file_SC_23095_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23095_proto_rawDesc), len(file_SC_23095_proto_rawDesc)))
	})
	return file_SC_23095_proto_rawDescData
}

var file_SC_23095_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23095_proto_goTypes = []any{
	(*SC_23095)(nil),    // 0: belfast.SC_23095
	(*PTGC_PLAYER)(nil), // 1: belfast.PTGC_PLAYER
	(*PTGC_TEAM)(nil),   // 2: belfast.PTGC_TEAM
}
var file_SC_23095_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23095.player_list:type_name -> belfast.PTGC_PLAYER
	2, // 1: belfast.SC_23095.team_list:type_name -> belfast.PTGC_TEAM
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_23095_proto_init() }
func file_SC_23095_proto_init() {
	if File_SC_23095_proto != nil {
		return
	}
	file_PTGC_PLAYER_proto_init()
	file_PTGC_TEAM_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23095_proto_rawDesc), len(file_SC_23095_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23095_proto_goTypes,
		DependencyIndexes: file_SC_23095_proto_depIdxs,
		MessageInfos:      file_SC_23095_proto_msgTypes,
	}.Build()
	File_SC_23095_proto = out.File
	file_SC_23095_proto_goTypes = nil
	file_SC_23095_proto_depIdxs = nil
}
