// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23404.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23404 struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Timestamp     *uint32                       `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	PlayerEvents  []*PTGC_BID_KING_PLAYER_EVENT `protobuf:"bytes,2,rep,name=player_events,json=playerEvents" json:"player_events,omitempty"`
	EventEffect   *PTGC_BID_KING_EVENT_EFFECT   `protobuf:"bytes,3,opt,name=event_effect,json=eventEffect" json:"event_effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23404) Reset() {
	*x = SC_23404{}
	mi := &file_SC_23404_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23404) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23404) ProtoMessage() {}

func (x *SC_23404) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23404_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23404.ProtoReflect.Descriptor instead.
func (*SC_23404) Descriptor() ([]byte, []int) {
	return file_SC_23404_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23404) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *SC_23404) GetPlayerEvents() []*PTGC_BID_KING_PLAYER_EVENT {
	if x != nil {
		return x.PlayerEvents
	}
	return nil
}

func (x *SC_23404) GetEventEffect() *PTGC_BID_KING_EVENT_EFFECT {
	if x != nil {
		return x.EventEffect
	}
	return nil
}

var File_SC_23404_proto protoreflect.FileDescriptor

const file_SC_23404_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23404.proto\x12\abelfast\x1a PTGC_BID_KING_EVENT_EFFECT.proto\x1a PTGC_BID_KING_PLAYER_EVENT.proto\"\xba\x01\n" +
	"\bSC_23404\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x02(\rR\ttimestamp\x12H\n" +
	"\rplayer_events\x18\x02 \x03(\v2#.belfast.PTGC_BID_KING_PLAYER_EVENTR\fplayerEvents\x12F\n" +
	"\fevent_effect\x18\x03 \x01(\v2#.belfast.PTGC_BID_KING_EVENT_EFFECTR\veventEffectB\fZ\n" +
	"./protobuf"

var (
	file_SC_23404_proto_rawDescOnce sync.Once
	file_SC_23404_proto_rawDescData []byte
)

func file_SC_23404_proto_rawDescGZIP() []byte {
	file_SC_23404_proto_rawDescOnce.Do(func() {
		file_SC_23404_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23404_proto_rawDesc), len(file_SC_23404_proto_rawDesc)))
	})
	return file_SC_23404_proto_rawDescData
}

var file_SC_23404_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23404_proto_goTypes = []any{
	(*SC_23404)(nil),                   // 0: belfast.SC_23404
	(*PTGC_BID_KING_PLAYER_EVENT)(nil), // 1: belfast.PTGC_BID_KING_PLAYER_EVENT
	(*PTGC_BID_KING_EVENT_EFFECT)(nil), // 2: belfast.PTGC_BID_KING_EVENT_EFFECT
}
var file_SC_23404_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23404.player_events:type_name -> belfast.PTGC_BID_KING_PLAYER_EVENT
	2, // 1: belfast.SC_23404.event_effect:type_name -> belfast.PTGC_BID_KING_EVENT_EFFECT
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_23404_proto_init() }
func file_SC_23404_proto_init() {
	if File_SC_23404_proto != nil {
		return
	}
	file_PTGC_BID_KING_EVENT_EFFECT_proto_init()
	file_PTGC_BID_KING_PLAYER_EVENT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23404_proto_rawDesc), len(file_SC_23404_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23404_proto_goTypes,
		DependencyIndexes: file_SC_23404_proto_depIdxs,
		MessageInfos:      file_SC_23404_proto_msgTypes,
	}.Build()
	File_SC_23404_proto = out.File
	file_SC_23404_proto_goTypes = nil
	file_SC_23404_proto_depIdxs = nil
}
