// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23101.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23101 struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PlayerList    []*PTGC_CHEAT_BAR_PLAYER `protobuf:"bytes,1,rep,name=player_list,json=playerList" json:"player_list,omitempty"`
	RealCard      *uint32                  `protobuf:"varint,2,req,name=real_card,json=realCard" json:"real_card,omitempty"`
	CardList      []*PTGC_CHEAT_BAR_CARD   `protobuf:"bytes,3,rep,name=card_list,json=cardList" json:"card_list,omitempty"`
	UserId        *uint32                  `protobuf:"varint,4,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AutoTime      *uint32                  `protobuf:"varint,5,req,name=auto_time,json=autoTime" json:"auto_time,omitempty"`
	StartTime     *uint32                  `protobuf:"varint,6,req,name=start_time,json=startTime" json:"start_time,omitempty"`
	RoomType      *uint32                  `protobuf:"varint,7,req,name=room_type,json=roomType" json:"room_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23101) Reset() {
	*x = SC_23101{}
	mi := &file_SC_23101_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23101) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23101) ProtoMessage() {}

func (x *SC_23101) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23101_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23101.ProtoReflect.Descriptor instead.
func (*SC_23101) Descriptor() ([]byte, []int) {
	return file_SC_23101_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23101) GetPlayerList() []*PTGC_CHEAT_BAR_PLAYER {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *SC_23101) GetRealCard() uint32 {
	if x != nil && x.RealCard != nil {
		return *x.RealCard
	}
	return 0
}

func (x *SC_23101) GetCardList() []*PTGC_CHEAT_BAR_CARD {
	if x != nil {
		return x.CardList
	}
	return nil
}

func (x *SC_23101) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SC_23101) GetAutoTime() uint32 {
	if x != nil && x.AutoTime != nil {
		return *x.AutoTime
	}
	return 0
}

func (x *SC_23101) GetStartTime() uint32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *SC_23101) GetRoomType() uint32 {
	if x != nil && x.RoomType != nil {
		return *x.RoomType
	}
	return 0
}

var File_SC_23101_proto protoreflect.FileDescriptor

const file_SC_23101_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23101.proto\x12\abelfast\x1a\x19PTGC_CHEAT_BAR_CARD.proto\x1a\x1bPTGC_CHEAT_BAR_PLAYER.proto\"\x95\x02\n" +
	"\bSC_23101\x12?\n" +
	"\vplayer_list\x18\x01 \x03(\v2\x1e.belfast.PTGC_CHEAT_BAR_PLAYERR\n" +
	"playerList\x12\x1b\n" +
	"\treal_card\x18\x02 \x02(\rR\brealCard\x129\n" +
	"\tcard_list\x18\x03 \x03(\v2\x1c.belfast.PTGC_CHEAT_BAR_CARDR\bcardList\x12\x17\n" +
	"\auser_id\x18\x04 \x02(\rR\x06userId\x12\x1b\n" +
	"\tauto_time\x18\x05 \x02(\rR\bautoTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x02(\rR\tstartTime\x12\x1b\n" +
	"\troom_type\x18\a \x02(\rR\broomTypeB\fZ\n" +
	"./protobuf"

var (
	file_SC_23101_proto_rawDescOnce sync.Once
	file_SC_23101_proto_rawDescData []byte
)

func file_SC_23101_proto_rawDescGZIP() []byte {
	file_SC_23101_proto_rawDescOnce.Do(func() {
		file_SC_23101_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23101_proto_rawDesc), len(file_SC_23101_proto_rawDesc)))
	})
	return file_SC_23101_proto_rawDescData
}

var file_SC_23101_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23101_proto_goTypes = []any{
	(*SC_23101)(nil),              // 0: belfast.SC_23101
	(*PTGC_CHEAT_BAR_PLAYER)(nil), // 1: belfast.PTGC_CHEAT_BAR_PLAYER
	(*PTGC_CHEAT_BAR_CARD)(nil),   // 2: belfast.PTGC_CHEAT_BAR_CARD
}
var file_SC_23101_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23101.player_list:type_name -> belfast.PTGC_CHEAT_BAR_PLAYER
	2, // 1: belfast.SC_23101.card_list:type_name -> belfast.PTGC_CHEAT_BAR_CARD
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SC_23101_proto_init() }
func file_SC_23101_proto_init() {
	if File_SC_23101_proto != nil {
		return
	}
	file_PTGC_CHEAT_BAR_CARD_proto_init()
	file_PTGC_CHEAT_BAR_PLAYER_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23101_proto_rawDesc), len(file_SC_23101_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23101_proto_goTypes,
		DependencyIndexes: file_SC_23101_proto_depIdxs,
		MessageInfos:      file_SC_23101_proto_msgTypes,
	}.Build()
	File_SC_23101_proto = out.File
	file_SC_23101_proto_goTypes = nil
	file_SC_23101_proto_depIdxs = nil
}
