// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23401.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23401 struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	StartTime         *uint32                     `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Round             *uint32                     `protobuf:"varint,2,req,name=round" json:"round,omitempty"`
	PublicEventEffect *PTGC_BID_KING_EVENT_EFFECT `protobuf:"bytes,3,req,name=public_event_effect,json=publicEventEffect" json:"public_event_effect,omitempty"`
	EventList         []uint32                    `protobuf:"varint,4,rep,name=event_list,json=eventList" json:"event_list,omitempty"`
	Timestamp         *uint32                     `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SC_23401) Reset() {
	*x = SC_23401{}
	mi := &file_SC_23401_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23401) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23401) ProtoMessage() {}

func (x *SC_23401) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23401_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23401.ProtoReflect.Descriptor instead.
func (*SC_23401) Descriptor() ([]byte, []int) {
	return file_SC_23401_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23401) GetStartTime() uint32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *SC_23401) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *SC_23401) GetPublicEventEffect() *PTGC_BID_KING_EVENT_EFFECT {
	if x != nil {
		return x.PublicEventEffect
	}
	return nil
}

func (x *SC_23401) GetEventList() []uint32 {
	if x != nil {
		return x.EventList
	}
	return nil
}

func (x *SC_23401) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_SC_23401_proto protoreflect.FileDescriptor

const file_SC_23401_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23401.proto\x12\abelfast\x1a PTGC_BID_KING_EVENT_EFFECT.proto\"\xd1\x01\n" +
	"\bSC_23401\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\rR\tstartTime\x12\x14\n" +
	"\x05round\x18\x02 \x02(\rR\x05round\x12S\n" +
	"\x13public_event_effect\x18\x03 \x02(\v2#.belfast.PTGC_BID_KING_EVENT_EFFECTR\x11publicEventEffect\x12\x1d\n" +
	"\n" +
	"event_list\x18\x04 \x03(\rR\teventList\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x02(\rR\ttimestampB\fZ\n" +
	"./protobuf"

var (
	file_SC_23401_proto_rawDescOnce sync.Once
	file_SC_23401_proto_rawDescData []byte
)

func file_SC_23401_proto_rawDescGZIP() []byte {
	file_SC_23401_proto_rawDescOnce.Do(func() {
		file_SC_23401_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23401_proto_rawDesc), len(file_SC_23401_proto_rawDesc)))
	})
	return file_SC_23401_proto_rawDescData
}

var file_SC_23401_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23401_proto_goTypes = []any{
	(*SC_23401)(nil),                   // 0: belfast.SC_23401
	(*PTGC_BID_KING_EVENT_EFFECT)(nil), // 1: belfast.PTGC_BID_KING_EVENT_EFFECT
}
var file_SC_23401_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23401.public_event_effect:type_name -> belfast.PTGC_BID_KING_EVENT_EFFECT
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_23401_proto_init() }
func file_SC_23401_proto_init() {
	if File_SC_23401_proto != nil {
		return
	}
	file_PTGC_BID_KING_EVENT_EFFECT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23401_proto_rawDesc), len(file_SC_23401_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23401_proto_goTypes,
		DependencyIndexes: file_SC_23401_proto_depIdxs,
		MessageInfos:      file_SC_23401_proto_msgTypes,
	}.Build()
	File_SC_23401_proto = out.File
	file_SC_23401_proto_goTypes = nil
	file_SC_23401_proto_depIdxs = nil
}
