// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_23408.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_23408 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidUserId     *uint32                `protobuf:"varint,1,req,name=bid_user_id,json=bidUserId" json:"bid_user_id,omitempty"`
	BidPrice      *uint32                `protobuf:"varint,2,req,name=bid_price,json=bidPrice" json:"bid_price,omitempty"`
	ItemList      []*PTGC_BID_KING_ITEM  `protobuf:"bytes,3,rep,name=item_list,json=itemList" json:"item_list,omitempty"`
	ChangeGold    *int32                 `protobuf:"varint,4,req,name=change_gold,json=changeGold" json:"change_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_23408) Reset() {
	*x = SC_23408{}
	mi := &file_SC_23408_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_23408) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_23408) ProtoMessage() {}

func (x *SC_23408) ProtoReflect() protoreflect.Message {
	mi := &file_SC_23408_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_23408.ProtoReflect.Descriptor instead.
func (*SC_23408) Descriptor() ([]byte, []int) {
	return file_SC_23408_proto_rawDescGZIP(), []int{0}
}

func (x *SC_23408) GetBidUserId() uint32 {
	if x != nil && x.BidUserId != nil {
		return *x.BidUserId
	}
	return 0
}

func (x *SC_23408) GetBidPrice() uint32 {
	if x != nil && x.BidPrice != nil {
		return *x.BidPrice
	}
	return 0
}

func (x *SC_23408) GetItemList() []*PTGC_BID_KING_ITEM {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *SC_23408) GetChangeGold() int32 {
	if x != nil && x.ChangeGold != nil {
		return *x.ChangeGold
	}
	return 0
}

var File_SC_23408_proto protoreflect.FileDescriptor

const file_SC_23408_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_23408.proto\x12\abelfast\x1a\x18PTGC_BID_KING_ITEM.proto\"\xa2\x01\n" +
	"\bSC_23408\x12\x1e\n" +
	"\vbid_user_id\x18\x01 \x02(\rR\tbidUserId\x12\x1b\n" +
	"\tbid_price\x18\x02 \x02(\rR\bbidPrice\x128\n" +
	"\titem_list\x18\x03 \x03(\v2\x1b.belfast.PTGC_BID_KING_ITEMR\bitemList\x12\x1f\n" +
	"\vchange_gold\x18\x04 \x02(\x05R\n" +
	"changeGoldB\fZ\n" +
	"./protobuf"

var (
	file_SC_23408_proto_rawDescOnce sync.Once
	file_SC_23408_proto_rawDescData []byte
)

func file_SC_23408_proto_rawDescGZIP() []byte {
	file_SC_23408_proto_rawDescOnce.Do(func() {
		file_SC_23408_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_23408_proto_rawDesc), len(file_SC_23408_proto_rawDesc)))
	})
	return file_SC_23408_proto_rawDescData
}

var file_SC_23408_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_23408_proto_goTypes = []any{
	(*SC_23408)(nil),           // 0: belfast.SC_23408
	(*PTGC_BID_KING_ITEM)(nil), // 1: belfast.PTGC_BID_KING_ITEM
}
var file_SC_23408_proto_depIdxs = []int32{
	1, // 0: belfast.SC_23408.item_list:type_name -> belfast.PTGC_BID_KING_ITEM
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SC_23408_proto_init() }
func file_SC_23408_proto_init() {
	if File_SC_23408_proto != nil {
		return
	}
	file_PTGC_BID_KING_ITEM_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_23408_proto_rawDesc), len(file_SC_23408_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_23408_proto_goTypes,
		DependencyIndexes: file_SC_23408_proto_depIdxs,
		MessageInfos:      file_SC_23408_proto_msgTypes,
	}.Build()
	File_SC_23408_proto = out.File
	file_SC_23408_proto_goTypes = nil
	file_SC_23408_proto_depIdxs = nil
}
