// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SHIPINFO_IN_DORM.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SHIPINFO_IN_DORM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Floor         *uint32                `protobuf:"varint,2,req,name=floor" json:"floor,omitempty"`
	PopIcon       *uint32                `protobuf:"varint,3,req,name=pop_icon,json=popIcon" json:"pop_icon,omitempty"`
	PopIntimacy   *uint32                `protobuf:"varint,4,req,name=pop_intimacy,json=popIntimacy" json:"pop_intimacy,omitempty"`
	Tid           *uint32                `protobuf:"varint,5,req,name=tid" json:"tid,omitempty"`
	SkinId        *uint32                `protobuf:"varint,6,req,name=skin_id,json=skinId" json:"skin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHIPINFO_IN_DORM) Reset() {
	*x = SHIPINFO_IN_DORM{}
	mi := &file_SHIPINFO_IN_DORM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHIPINFO_IN_DORM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHIPINFO_IN_DORM) ProtoMessage() {}

func (x *SHIPINFO_IN_DORM) ProtoReflect() protoreflect.Message {
	mi := &file_SHIPINFO_IN_DORM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHIPINFO_IN_DORM.ProtoReflect.Descriptor instead.
func (*SHIPINFO_IN_DORM) Descriptor() ([]byte, []int) {
	return file_SHIPINFO_IN_DORM_proto_rawDescGZIP(), []int{0}
}

func (x *SHIPINFO_IN_DORM) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SHIPINFO_IN_DORM) GetFloor() uint32 {
	if x != nil && x.Floor != nil {
		return *x.Floor
	}
	return 0
}

func (x *SHIPINFO_IN_DORM) GetPopIcon() uint32 {
	if x != nil && x.PopIcon != nil {
		return *x.PopIcon
	}
	return 0
}

func (x *SHIPINFO_IN_DORM) GetPopIntimacy() uint32 {
	if x != nil && x.PopIntimacy != nil {
		return *x.PopIntimacy
	}
	return 0
}

func (x *SHIPINFO_IN_DORM) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

func (x *SHIPINFO_IN_DORM) GetSkinId() uint32 {
	if x != nil && x.SkinId != nil {
		return *x.SkinId
	}
	return 0
}

var File_SHIPINFO_IN_DORM_proto protoreflect.FileDescriptor

const file_SHIPINFO_IN_DORM_proto_rawDesc = "" +
	"\n" +
	"\x16SHIPINFO_IN_DORM.proto\x12\abelfast\"\xa1\x01\n" +
	"\x10SHIPINFO_IN_DORM\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x14\n" +
	"\x05floor\x18\x02 \x02(\rR\x05floor\x12\x19\n" +
	"\bpop_icon\x18\x03 \x02(\rR\apopIcon\x12!\n" +
	"\fpop_intimacy\x18\x04 \x02(\rR\vpopIntimacy\x12\x10\n" +
	"\x03tid\x18\x05 \x02(\rR\x03tid\x12\x17\n" +
	"\askin_id\x18\x06 \x02(\rR\x06skinIdB\fZ\n" +
	"./protobuf"

var (
	file_SHIPINFO_IN_DORM_proto_rawDescOnce sync.Once
	file_SHIPINFO_IN_DORM_proto_rawDescData []byte
)

func file_SHIPINFO_IN_DORM_proto_rawDescGZIP() []byte {
	file_SHIPINFO_IN_DORM_proto_rawDescOnce.Do(func() {
		file_SHIPINFO_IN_DORM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SHIPINFO_IN_DORM_proto_rawDesc), len(file_SHIPINFO_IN_DORM_proto_rawDesc)))
	})
	return file_SHIPINFO_IN_DORM_proto_rawDescData
}

var file_SHIPINFO_IN_DORM_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SHIPINFO_IN_DORM_proto_goTypes = []any{
	(*SHIPINFO_IN_DORM)(nil), // 0: belfast.SHIPINFO_IN_DORM
}
var file_SHIPINFO_IN_DORM_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SHIPINFO_IN_DORM_proto_init() }
func file_SHIPINFO_IN_DORM_proto_init() {
	if File_SHIPINFO_IN_DORM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SHIPINFO_IN_DORM_proto_rawDesc), len(file_SHIPINFO_IN_DORM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SHIPINFO_IN_DORM_proto_goTypes,
		DependencyIndexes: file_SHIPINFO_IN_DORM_proto_depIdxs,
		MessageInfos:      file_SHIPINFO_IN_DORM_proto_msgTypes,
	}.Build()
	File_SHIPINFO_IN_DORM_proto = out.File
	file_SHIPINFO_IN_DORM_proto_goTypes = nil
	file_SHIPINFO_IN_DORM_proto_depIdxs = nil
}
